In [48]:
import numpy as np
d = 0.9 
adj = np.array([[0,1/2,1/2,0,0,0],[0,0,0,0,0,0],[1/3,1/3,0,0,1/3,0],[0,0,0,0,1/2,1/2],[0,0,0,1/2,0,1/2],[0,0,0,1,0,0]])
print("Adjacency Matrix: \n", adj, "\n\n")
n=len(adj)
for i in range(n):
    if any(adj[i])==0:
        for l in range(n):
            adj[i][l]=1/n
print("Stochastic Matrix:\n", adj, "\n\n")

E = np.ones((n,n))
sto=(1-d)*E/n+d*np.transpose(adj)
#print("Stochastic Matrix: \n",sto, "\n\n")


def pagerank(P,r):
        pagerank.count=getattr(pagerank,"count",1)
        Pk=np.dot(r,P)
        print("Page rank for Itr ",pagerank.count,": ",Pk,"\n")
        
        temp=0
        for i in range(len(Pk)):
                if(abs(Pk[i]-P[i])<0.05):    #0.05 is threshold value
                        temp=temp+1
        if(temp<len(Pk)):
                pagerank.count+=1
                pagerank(Pk,r)
        else:
                lst=[]
                for i in Pk:
                        lst.append(i)
                lst.sort(reverse=True)
                rank=[]
                for i in lst:
                        t=np.where(Pk==i)
                        rank.append(t)
                print("Total count for Iterations : ",pagerank.count,"\n\n")
                print("PageRank are: \n")
                for i in range(len(rank)):
                                    print(rank[i][0][0]+1,end=' ')
                print("\n")

initial_pr=(np.ones(6,dtype=float)/6)

r1=((1-d)*E)/6
r2=d*sto
r=r1+r2

pagerank(initial_pr, r)

Adjacency Matrix: 
 [[0.         0.5        0.5        0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]] 


Stochastic Matrix:
 [[0.         0.5        0.5        0.         0.         0.        ]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.33333333 0.33333333 0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.5        0.5       ]
 [0.         0.         0.         0.5        0.         0.5       ]
 [0.         0.         0.         1.         0.         0.        ]] 


Page rank for Itr  1 :  [0.09916667 0.16666667 0.12166667 0.25666667 0.16666667 0.18916667] 

Page rank for Itr  2 :  [0.087

In [49]:
import numpy as np
import math

def hits(A,H,L,Lt):
    hits.count=getattr(hits,"count",1)
    Ak=np.dot(np.dot(Lt,L),A)
    Hk=np.dot(np.dot(L,Lt),H)
    As=[]
    for i in Ak:
        As.append(i**2)
    Ak=Ak/float(math.sqrt(sum(As)))

    Hs=[]
    for i in Hk:
        Hs.append(i**2)
    Hk=Hk/float(math.sqrt(sum(Hs)))

    print("AS for itr ",hits.count,":\n",Ak,"\n")
    print("HS for itr ",hits.count,":\n",Hk,"\n")
    
    
    temp=0
    for i in range(len(Ak)):
        if(abs(Ak[i]-A[i])<0.05 and abs(Hk[i]-H[i])<0.05):
            temp=temp+1
    if(temp<len(Ak)):
        hits.count+=1
        hits(Ak,Hk,L,Lt)
    else:
        print("\nFinal Authority and Hub score is same as the last generated score")
        print("\nTotal number of Iterations are: ",hits.count)
        
        

L=np.array([[0,1,1,0,0,0],
                    [0,0,0,0,0,0],
                    [1,1,0,0,1,0],
                    [0,0,0,0,1,1],
                    [0,0,0,1,0,1],
                    [0,0,0,1,0,0]])

print("Adjency Matrix : \n\n",L,"\n\n")
Lt=L.transpose()
Ain=np.ones(6)
Hin=np.ones(6)
hits(Ain,Hin,L,Lt)


Adjency Matrix : 

 [[0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [1 1 0 0 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 1 0 0]] 


AS for itr  1 :
 [0.31980107 0.53300179 0.21320072 0.31980107 0.53300179 0.42640143] 

HS for itr  1 :
 [0.35856858 0.         0.5976143  0.47809144 0.47809144 0.23904572] 

AS for itr  2 :
 [0.34045882 0.5237828  0.18332398 0.2618914  0.57616108 0.41902624] 

HS for itr  2 :
 [0.32781098 0.         0.65562195 0.50661696 0.41721397 0.17880599] 

AS for itr  3 :
 [0.35124594 0.52367576 0.17242982 0.22990643 0.59392495 0.40872255] 

HS for itr  3 :
 [0.3219924  0.         0.68789287 0.51226064 0.37321847 0.14636018] 


Final Authority and Hub score is same as the last generated score

Total number of Iterations are:  3
